<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2966" started-at="2021-11-11T20:32:36Z" finished-at="2021-11-11T20:32:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2966" started-at="2021-11-11T20:32:36Z" finished-at="2021-11-11T20:32:39Z">
      <class name="in.amazon.testscripts.invaliduserTest">
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:in.amazon.testscripts.invaliduserTest@2a70a3d8]" name="launchApplication" is-config="true" duration-ms="2786" started-at="2021-11-11T20:32:36Z" finished-at="2021-11-11T20:32:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="invalidUserShouldNotBeAbleToLogin()[pri:0, instance:in.amazon.testscripts.invaliduserTest@2a70a3d8]" name="invalidUserShouldNotBeAbleToLogin" duration-ms="77" started-at="2021-11-11T20:32:38Z" finished-at="2021-11-11T20:32:39Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at org.openqa.selenium.interactions.Actions.<init>(Actions.java:65)
at in.amazon.pages.LandingPage.<init>(LandingPage.java:28)
at in.amazon.testscripts.invaliduserTest.invalidUserShouldNotBeAbleToLogin(invaliduserTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserShouldNotBeAbleToLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:in.amazon.testscripts.invaliduserTest@2a70a3d8]" name="closeBrowser" is-config="true" duration-ms="75" started-at="2021-11-11T20:32:39Z" finished-at="2021-11-11T20:32:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- in.amazon.testscripts.invaliduserTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
